### ISSUE TITLE
Why not join JuliaDynamics?

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/CausalityTools.jl#117]
Hey there,

I was thinking about our discussion on how having these packages in an org can help visibility, and I am wondering: why not just join JuliaDynamics? Its already a big org with a lot of followers and people working on it, plus it is directly connected with what CausalityTools.jl tries to achieve. Heck, you literally interface `Dataset` and `DynamicalSystem`!

What do you think?

**Comment by kahaaga** [comment]
I've discussed this with the group, and we agree that joining JuliaDynamics is a good idea! 

How would this work in practice? Finish up documentation improvements and v1.0 stuff, then join?  

I'm hesitant to make a big fuzz about it until things on the user-end are presentable and easy-to-understand, the same way DynamicalSystems is. What do you think?

**Comment by Datseris** [comment]
Here are the steps I think will make this easiest:

1. Transfer the relevant packages to the org (don't worry about ownership, I'll make a team "causalitytools" where you get owner privileges for all packages there)
2. Continue working normally on 1.0 and I also do contributions to the docs. (Notice, there is no "breakage" when transferring packages, installing them will work normally as before).
3. Make logo (**extremely important!!!**, and I know just the guy for it)
4. Move all embedding to common package: DelayEmbeddings.jl
4. Release/tag 1.0.
4. Announce on discourse. 

I can take care of the announcement and tag you there, I have "announced" quite a lot of packages.
