### ISSUE TITLE
Merge customembed(pts, positions::Positions, lags::Lags) in DelayEmbeddings.jl ?

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/CausalityTools.jl#118]
I am reading the documentation, and so far seems to me that the custom embeddings are not that different from `embed`. In fact, since there is already a package DelayEmbeddings.jl, such delay coordinate embeddings with multiple vectors fit there as well. 

Is there something else that StateSpaceReconstruction offers, besides the ability to make this `customembed`? Based on what the function does, this should be doable in at most 100 lines of code in DelayEmbeddings.jl. What do you think about merging `customembed` into DelayEmbeddings (and in fact keeping the name `embed`, since multiple dispatch is enough to dispatch on types like `Positions`)? This would remove one package from installation and dependencies list (`StateSpaceReconstruction`), and also remove problems like
```

julia> using CausalityTools

julia> WARNING: both StateSpaceReconstruction and DynamicalSystems export "dimension"; uses of it in module CausalityTools must be qualified
WARNING: both StateSpaceReconstruction and DynamicalSystems export "AbstractEmbedding"; uses of it in module CausalityTools must be qualified
```

**Comment by kahaaga** [comment]
That sounds like a good idea! 

Most of the functionality of StateSpaceReconstruction has been moved to `CausalityToolsBase`, but except `customembed`, some migration still remains (code related to triangulation partitions).  I am planning to deprecate StateSpaceReconstruction entirely in the future. Moving embedding stuff to `DelayEmbeddings` will help with that process, so I am very up for it! 

## My thoughts

Merging `customembed` with `embed` by dispatching on `Lags` and `Positions` is a good idea.   What would the function signature be? For me, it would be useful to do:

1. `embed(x::Dataset, lags::Lags, pos::Positions)`, mapping the columns of `x` to different coordinate axes of the embedding with different `lags`. This should also work if points are given as a vector of static `MVector` or `SVector` (I guess for `Dataset`s points are internally represented as an array of `SVector` points)?)
2. `embed(x::Vector{Vector}, lags::Lags, pos::Positions)`. The same, but provide 
data as a vector of column vectors (each column vector being a time series).

**Comment by Datseris** [comment]
Cool! I've invited to the JuliaDynamics org and given you permissions for DelayEmbeddings so you don't have to work on your own fork. 

`Dataset` is a `Vector{<:SVector}` at the moment, but it is kind of trivial to extend to accept also `MVector`s, but only if there is an actual reason to do that. At the moment I don't see why this would be useful.

The first call signature is quite straightforward to implement. The second is also fine, but it raises some ambiguity that has to be clarified: are the inner vectors data points or entire variables?

**Comment by kahaaga** [comment]
Perfect, thanks! 

Some algorithms may require manipulating individual points after the `Dataset` has been initialised. For example, when working with the triangulation transfer entropy estimators, sometimes points must be slightly moved around for good triangulations to be constructed. In this case, having `MVector`s would be useful, so I don't have to convert back and forth between `Vector` and `SVector`. It is not crucial though, so I'm not sure if it's worth it. Would there be any performance penalty by allowing `MVector`s? 

For the second call signature, the inner vectors would be entire variables (i. e. what columns are for `Dataset`).

**Comment by Datseris** [comment]
There is no performance penalty, there is only "time penalty", meaning developer's time :D At the moment Dataset is defined such as to have a vector of static vectors, see here: https://github.com/JuliaDynamics/DelayEmbeddings.jl/blob/master/src/dataset.jl#L122 

I guess actually it is quite trivial... just make the inner vectors a Type parameter of `Dataset` and make sure tests pass. Shouldn't take more than 20 minutes of dev time. The plan would be to make

```julia
struct Dataset{D, T, U <: Union{SVector, MVector}} <: AbstractDataset{D,T}
    data::Vector{U{D,T}}
end
```

**Comment by kahaaga** [comment]
Since we're now using StateSpaceSets.jl, this can be closed.  The possibility to use MVectors can be opened as a separate issue there if the need arises.
