### ISSUE TITLE
Convenience method of transfer entropy does not work

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/CausalityTools.jl#120]
From here https://kahaaga.github.io/CausalityTools.jl/dev/transferentropy/convenience_methods_te/  the docs list:
```
transferentropy(source::AbstractArray{<:Real, 1}, 
    response::AbstractArray{<:Real, 1}, 
    k::Int, l::Int, m::Int,
    binning_scheme::Union{RectangularBinning, Vector{RectangularBinning}}; 
    summary_statistic::Function = StatsBase.mean,
    η::Int = 1, τ::Int = 1, 
    estimator::BinningTransferEntropyEstimator = VisitationFrequency(b = 2)) -> FLoat64
```

however this doesn't work if one does
```
x1, x2 = rand(100), rand(100)
transferentropy(X1, X2, 1, 1, 1, RectangularBinning(10))
```
after digging around a bit I found that the actual signature is:
```
transferentropy(X1, X2, RectangularBinning(10), 1, 1, 1)
```

**Comment by kahaaga** [comment]
Thanks for spotting this one! I will get out a fix shortly.

## Future convenience function for TE 

I actually have re-done the convenience function entirely for transfer entropy for the 1.0 release. The function signature will be:

```julia
transferentropy(source, target, 
        p::EmbeddingTE, 
        binning_scheme::Union{RectangularBinning, Vector{RectangularBinning}, BinningHeuristic}; 
        summary_statistic::Function = StatsBase.mean,
        estimator::BET = VisitationFrequency(b = 2)
```

### Embedding for TE 

Here, all information about the embedding is gathered in a struct. This way, the user can either use fixed dimensions/lags for each marginal or automatically find an "optimal" delay/dimension for each marginal separately. The exact type signature for `EmbeddingTE` is still experimental,  but will be out soon (a decision on notation must be made, ref your comment in #119). 

The idea is to dispatch on an `EmbeddingMETHOD` type for each causality method, e.g. one for the predictive asymmetry (`EmbeddingPA`), one for cross mapping (`EmbeddingCCM`), one for joint distance distribution (`EmbeddingJDD`), etc. Delay embeddings are used for many methods, but this way the semantic meaning of the embedding parameters will be explicit by the type. 

### Binning for TE 

Introducing binning heuristic types (`BinningHeuristic` subtypes) will also enable automatic determination of the binning scheme. 

For example, Krakovska et al. uses an heuristic from Palus that scales according to total dimension and the number of the point in the time series to dictate the number of bins in the partition for TE, which would be indicated by a `PalusLimit` type.  

This only allows heuristic approaches for now, but could use more robust optimisation schemes in the future.

**Comment by Datseris** [comment]
Before that, can we talk about the design complexity in a more general sense, which also ties with  #94 ? I want to quickly mention the Julia golden standard: *"a thing should be done in one way, the most intuitive way"*. In general I fully agree with this, as it makes everything more transparent and easier to learn. Of course, sometimes some convenience functions are nice. 

Now to the transfer entropy. I hope we agree that to go from having a bunch of timeseries to having a value for the transfer entropy, one has to do the following steps, as reflected also in the docs: 

0. Specificy in your own brain what is your target and source. I strongly believe that this should not be done from the side of the software. THe user should specify that solely based on choosing the input arguments. 

1. Create a generalised delay reconstruction from the input data, which in fact means to choose the values of `d` and `τ` for the Future, Target, Source (and also Conditional). This is the point where a "convenience" function could be useful. But allowing to many ways that do this, **while having the same result** can lead to confusion.

2. Specify discretization scheme. Default arguments are useful here.

3. Choose the estimator.

My feeling so far is that there are many (perhaps too many) ways to do these steps. For example there are so many ways to perform step 1 that I am honestly confused. Another problem is step 3 of here: https://kahaaga.github.io/CausalityTools.jl/dev/transferentropy/overview_te/  , which for some reason takes the natural idea of "the order of inputs matters" to "map them without caring about the order". I think just having one, unique ordering in the calculation of transfer entropy that always goes `T, S` should make things clearer. 

At the moment I still remain very much confused about all the possible ways one can do these computations and steps. If we are able to reduce them, it will be of general use I think.

**Comment by Datseris** [comment]
By the way I really like the interface you present:
```
transferentropy(source, target, p::EmbeddingTE, binning_scheme)
```

provided that this `p::EmbeddingTE` can really be made with "only one way".

**Comment by kahaaga** [comment]
I agree that there should be only one way of estimating the transfer entropy that is exposed to the end-user. My intent was for the `transferentropy(source, target, p::EmbeddingTE, binning_scheme)` interface to be "the way". 

Currently, I have settled on the following for `EmbeddingTE` (now adjusted for the new notation we discussed in #119):

```julia
Base.@kwdef struct EmbeddingTE
    # Dimensions may be fixed, or optimised according to some method
    dT::Union{Int, OptimiseDim} = 1
    dS::Union{Int, OptimiseDim} = 1
    dC::Union{Int, OptimiseDim} = 1
    d𝒯::Union{Int, OptimiseDim} = 1

    # Delays may be fixed, a vector of delays (if the the dimension of a marginal > 1, then
    # one may specify the delay for each coordinate axis separately), or optimised 
    # according to some method
    τT::Union{Int, Vector{Int}, OptimiseDelay} = -1
    τS::Union{Int, Vector{Int}, OptimiseDelay} = -1
    τC::Union{Int, Vector{Int}, OptimiseDelay} = -1
    η𝒯::Union{Int, Vector{Int}, OptimiseDelay} = 1
end
```

_Note: embedding delays must be negative, while prediction lags must be positive. Some input validation is therefore included in the constructor._

## Default TE

```julia
Base.@kwdef OptimiseDelay
    # Which method to use for delay estimation when estimating dimension? Must be a method 
    # accepted by`DynamicalSystems.estimate_delay`.
    method_delay::String = "ac_min"

    # Estimate for lags 1:floor(Int, length(time_series)*maxdelay_frac). This allows
    # adjustment based on input time series length (which may be variable and not 
    # known beforehand when creating a OptimiseDelay instance)
    maxdelay_frac = 0.1
end
```

For a default analysis, the user would then do 

```julia
x, y = rand(100), rand(100)
binning = .... # some fixed binning or some binning heuristic
transferentropy(x, y, EmbeddingTE(), binning)
```

## Optimising marginals 

Optimisation should also be possible. I'm currently defined `OptimiseDim` and `OptimiseDelay` as follows.

```julia
Base.@kwdef OptimiseDim
    # Which method to use for dimension estimation? Must be a method 
    # accepted by`DynamicalSystems.estimate_dimension`.
    method_dim::String = "f1nn"
    
    # Select optimal dimension from possible dimensions 2:max_dim
    max_dim::Int = 7

    # Which method to use for delay estimation when estimating dimension? Must be a method 
    # accepted by`DynamicalSystems.estimate_delay`.
    method_delay::String = "ac_min"

    # Estimate for lags 1:floor(Int, length(time_series)*maxdelay_frac). This allows
    # adjustment based on input time series length (which may be variable and not 
    # known beforehand when creating a OptimiseDelay instance)
    maxdelay_frac = 0.1
end
```


Optimising the target present/past marginal is then done by

```julia
emb = EmbeddingTE(dT = OptimiseDim(), τT = OptimiseDelay())
binning = .... # some fixed binning or some binning heuristic
transferentropy(x, y, emb, binning)
```

The dimension/delay of the `T` marginal would be estimated from the input time series `x` and `y`. I found this approach useful when working with large datasets with varying input time series length.

Any thoughts on this?

**Comment by kahaaga** [comment]
Sorry, I missed your comment about `binning` being a keyword argument. I didn't know it was possible to dispatch on keyword arguments. Is this a very recent Julia feature? 

In any case, more keywords with default settings make things easier in my head, so having `binning` as a keyword argument sounds reasonable to me. 

There is a trade-off here, though.  Having default arguments for everything  makes things a "black box". From experience, such convenience will lead many users astray and make conclusions that are not warranted based on their data. To avoid, this some degree of effort / understanding should be required. Keeping `emb` as a regular argument, but making `binning` a keyword argument is a good trade-off in my eyes.

**Comment by Datseris** [comment]
The setup you have for `EmbeddingTE` I really like. We might be able to come up with a better name, but at the moment this is minor since we are not past 1.0. 

---

In all honestly, I am not completely sold on the `OptimzedDelay` and `OptimizedDimension` for two reasons:

1. They don't do something "new": they just directly pass all arguments to `estimate_delay/estimate_dim`. 
2. They act directly on the input arguments `x, y` and thus are not immediately necessary: one can always do `d = estimate_dimension(x)` and give this `d` to `EmbeddingTE`. If instead this process was happening to an internally generated timeseries it would be a different story, but here `x` is accessible from the user in a direct manner.
2. They add _a lot_ of complexity on the development side: many things to explicitly write and dispatch on. They also need a lot of diverse tests to catch errors, etc.
1. They somehow give the responsibility of the input parameter to "us" (the people that write the software), when this responsibility should on the user. 

On the other hand, I can see that they are useful shortcuts in their way, but with good documentation that points users to `estimate_delay/estimate_dimension`, it should be possible to offer the same outcome without having it done internally in `TransferEntropy`.

Is there some other reason for these types besides what I write here? Perhaps I am simply missing some future plan of sorts.

**Comment by Datseris** [comment]
I think the keyword `binning` or `binning_scheme` should have a different name. As we discussed, there are other schemes besides binning, e.g. the kernel estimation. We can just call it `method` . 

Even if it is a positional argument and not a keyword, still calling it `method` in the docstring is probably better.

**Comment by kahaaga** [comment]
> I think the keyword binning or binning_scheme should have a different name. As we discussed, there are other schemes besides binning, e.g. the kernel estimation. We can just call it method 

The keyword `binning` is I think we should keep, because it has very specific meaning for the binning-based estimators. However, we can move it to a more intuitive location. I suggest the following:


## A potential solution

Currently, the keyword that decides which estimation method is used is `estimator`. What if we make the `transferentropy` call signature method much simpler:

```julia
transferentropy(source, target, estimator) 
```



Then, we make all estimator-specific parameters (keyword) arguments to the estimator types? 

After all, the existing estimators already accept the keyword `b`, which controls the base of the logarithm used for the computations. 

## Binning based estimators

To perform binning-based estimation, you can now choose `estimator = VisitationFrequency()` or `estimator = TransferOperatorGrid()`. In the near future, there will also be the `TriangulationExact` and `TriangulationApprox` estimators. All these four estimators compute transfer entropy by estimating invariant densities over a grid (binning), but using different approaches.

Why not just make `binning` an keyword argument to the binning-based estimators? These are now just defined as 

```julia 
Base.@kwdef struct VisitationFrequency <: TransferEntropyEstimator
    """ base of the logarithm (e.g. b = 2 gives the transfer entropy in bits) """
    b::Real = 2
end

Base.@kwdef struct TransferOperatorGrid <: TransferEntropyEstimator
    """ base of the logarithm (e.g. b = 2 gives the transfer entropy in bits) """
    b::Real = 2
end
```

Instead, we'd do

```julia 
Base.@kwdef struct VisitationFrequency <: TransferEntropyEstimator
    """ base of the logarithm (e.g. b = 2 gives the transfer entropy in bits) """
    b::Real = 2
    
    # The summary statistic to use if multiple discretization schemes are given
    summary_statistic::Function = StatsBase.mean

    # The discretization scheme
    binning = .... # some binning heuristic
end

Base.@kwdef struct TransferOperatorGrid <: TransferEntropyEstimator
    """ base of the logarithm (e.g. b = 2 gives the transfer entropy in bits) """
    b::Int
 
    # The summary statistic to use if multiple discretization schemes are given
    summary_statistic::Function = StatsBase.mean

    # The discretization scheme
    binning = .... # some binning heuristic

end
```

`binning` can be a keyword defaulting to some binning heuristic. But it doesn't need to be a keyword argument. In fact, I think it should be positional, so that users are forced to actually think about how they discretize their state space reconstruction. I want to be very careful with not making the estimation too much of a black box.

That way, you would do 

```julia
x, y = rand(100), rand(100)

est = VisitationFrequency(binning = RectangularBinning(5))
transferentropy(x, y, est)
```

It makes much more sense in my mind to have every estimator-specific parameter as an argument to that estimator type. This reduces the number of arguments to `transferentropy`, 

## Kernel density estimator 

For an estimator using kernel density estimation, one could define (probably could choose a better name)

```julia
Base.@kwdef struct KernelDensityEst <: TransferEntropyEstimator
    """ base of the logarithm (e.g. b = 2 gives the transfer entropy in bits) """
    b::Number = 2
    
    # parameters for the kernel density estimator...
    ... 
end
```

```julia
x, y = rand(100), rand(100)

est = KernelDensityEst(b = 2, args...; kwargs...)
transferentropy(x, y, est)
```

## Nearest-neighbor estimator 

This is already implemented, but not available at the user-level yet.

```julia
@Base.kwdef struct NearestNeighbourMI <: TransferEntropyEstimator
    k1::Int = 2
    k2::Int = 3
    metric::Metric = Chebyshev()
    b::Number = 2
end
```

Using it:

```julia
x, y = rand(100), rand(100)

est = NearestNeighbourM(k1 = 5, k2 = 10)
transferentropy(x, y, est)
```

**Comment by kahaaga** [comment]
> Even if it is a positional argument and not a keyword, still calling it method in the docstring is probably better.

Is there a good reason to name the argument `method` (generic) rather than `estimator` (specific, and what you provide is an instance of a `TransferEntropyEstimator`)? 

I favor the latter, because the name of the argument reflects the type(s) it accepts.

**Comment by Datseris** [comment]
Alright, I agree with your suggestion. Seems reasonable for me, and we can document what scheme each estimator uses to estimate, e.g. binning or kernel or anything else.

For the signature:
```
transferentropy(source, target, estimator) 
```
I think the delay embedding parameters should be independent of the `estimator` and should be a dedicated argument, the `EmbeddingTE` that we have discussed here. Did you simply forget to write it in the expression or was the actual intend to include them as parameters of the estimator?

**Comment by kahaaga** [comment]
> I think the delay embedding parameters should be independent of the estimator and should be a dedicated argument, the EmbeddingTE that we have discussed here. Did you simply forget to write it in the expression or was the actual intend to include them as parameters of the estimator?

Sorry, I completely forgot about it. Of course, the embedding parameters should be a a dedicated argument, using the `EmbeddingTE` type we discussed. I imagine the signature will be 

```julia
transferentropy(x, y, emb::EmbeddingTE, estimator::TransferEntropyEstimator)
```

**Comment by kahaaga** [comment]
This is now outdated with the current master branch (which will be v1). Closing.
