### ISSUE TITLE
Move everything more complex than entropies to this package

### ISSUE THREAD

**Issue by kahaaga** [JuliaDynamics/CausalityTools.jl#173]
@Datseris I've been working on PRs to address https://github.com/JuliaDynamics/Entropies.jl/issues/107 both for TransferEntropy and CausalityTools (getting ready for Entropies v2). 

We discussed in various issues and PRs in Entropies.jl where things more complicated than entropies should go, and decided that CausalityTools should be the "umbrella package" where all these measures go.

What I realised while reworking TransferEntropy.jl is that it would be much, much nicer if *everything* that is not entropies goes in CausalityTools, including `mutualinfo`, `conditional_mutualinfo` and `transferentropy`. The extra package layer between Entropies and CausalityTools is not worth it. Why?
-  Every relevant update in Entropies also requires a PR to both TransferEntropy and CausalityTools
- I can't directly tag a new version of CausalityTools before the workflow for TransferEntropy is finished. Sometimes, that may take up to a whole day, depending on how sluggish the general registry workflows and tagbots are.
- Having everything here will make testing/compatibility much easier. 

The only counterargument I can think of is that TransferEntropy.jl is already an established package with some users. However, my outlined solution will probably save us some frustration and development time down the line. We can just add a deprecation warning to TransferEntropy.jl, direct users here, and release a new version of TransferEntropy.jl that freezes relevant downstream package versions.

This will make #169 irrelevant, but I'm ok with that.

What do you think, @Datseris?

**Comment by Datseris** [comment]
- Every relevant update in Entropies also requires a PR to both TransferEntropy and CausalityTools

Why? Why would either of these be updated if e.g. a new entropy method shows up? don't they work generically using te generic `probabilities, entropies` api?

- The only counterargument I can think of is that TransferEntropy.jl is already an established package with some users. 

We also use it in our book but that isn't a big deal. The published version remains in the general registry even if discontinued.

I am not sure what you mean by "everything" though. What happens to complexity measures for example?

But yes, I agree that all methods for **causal and correlation metrics between timeseries** can all go into CausalityTools.jl.

**Comment by kahaaga** [comment]
> I am not sure what you mean by "everything" though. What happens to complexity measures for example?

Sorry, I should have been more clear. What I want is to discontinue TransferEntropy and move its functions and estimators here. End of story. Complexity.jl and Entropies.jl stays as they are.

> Why? Why would either of these be updated if e.g. a new entropy method shows up? don't they work generically using te generic probabilities, entropies api?

For some information measures and entropy estimators they generically work (e.g. `transferentropy(::ValueHistogram)`). But for other entropy estimators, we need to implement specialized dispatch, e.g. `transferentropy(::SymbolicPermutation)` and `momentaryinformationtransfer(::SymbolicPermutation)` (coming soon). Specialized dispatch is necessary because there are some nuances in how permutation entropy is implemented, vs how permutation *transfer* entropy is implemented (concerning when/where the ordinal pattern encoding is done). In some cases, we can just compute stuff naively from marginal entropies, but in some cases, there are additional steps required.

> We also use it in our book but that isn't a big deal. The published version remains in the general registry even if discontinued.

Ah, that could be an issue. But the book was also published referring to an old version of Entropies, I guess, so this shouldn't be an issue as long as we give a deprecation warning?

**Comment by Datseris** [comment]
The book is published with a manifest.toml file, so I wouldn't worry about this much. (although I'm sure some people will have problems, as always)

 I am ok with porting eveyrthing to CausalityTools.jl. You can release then a dummy version patch increase in TransferEntropy.jl that just prints that everything is moved to CausalityTools.jl and the package is discontinued. (Of course, change nothing else in TE.jl - the source code should work exactly as before)

**Comment by kahaaga** [comment]
> I am ok with porting eveyrthing to CausalityTools.jl. You can release then a dummy version patch increase in TransferEntropy.jl that just prints that everything is moved to CausalityTools.jl and the package is discontinued. (Of course, change nothing else in TE.jl - the source code should work exactly as before)

Ok, I released TransferEntropy v1.10 a few days ago. This introduced no changes, but version-locked Entropies.jl to v1.2.
When we release Entropies v2, I will release a TransferEntropy v1.11 which changes no code, but just gives a deprecation warning and redirecting them here.

**Comment by kahaaga** [comment]
This is followed up in #174.
