### ISSUE TITLE
LaTeX formatting error in docstring for ``LocalPermutationTest``

### ISSUE THREAD

**Issue by bhannis** [JuliaDynamics/CausalityTools.jl#206]
On the master branch

**Comment by kahaaga** [comment]
@bhannis Where exactly is the formatting error? Do you have a screenshot? I can't see it.

**Comment by bhannis** [comment]
@kahaaga  Sorry, it is actually in the "Examples - Independence tests - LocalPermutationTest":

<img width="875" alt="image" src="https://user-images.githubusercontent.com/22274860/218040677-ac418fdc-835a-4727-a404-522b43604efc.png">
