### ISSUE TITLE
Tagging v2.0

### ISSUE THREAD

**Issue by kahaaga** [JuliaDynamics/CausalityTools.jl#258]
Hey @Datseris,

FYI: I think we've now covered everything our group can think of in terms of reviewing the current material. We will therefore tag 2.0 today and assign a Zenodo DOI to the repo, which we need for a paper we're submitting this week.

## Overall comments

The public API is divided into three parts, in increasing order of complexity:
### 1. **Association measures**. 
- Each measure (pairwise or conditional) is represented by its own type (`<: AssociationMeasure`). 
- Every measure also has its own dedicated function (e.g. `MIShannon` has `mutualinfo`, `TEShannon` has `transferentropy`).
- This type-based approach ensures automatic compatibility with independence tests and causal graph inference methods through multiple dispatch.
- Each measure type also serves as parameter containers. Therefore, functions like `mutualinfo`, `transferentropy`, `crossmap`, etc do not accept keywords. Instead, one would do `mutualinfo(MIShannon(; params...), est, x, y)`.

### 2. **Independence tests**. 

Once one has an association measure, it is nice to formally test whether its statistic is statistically significant. We therefore offer an independence testing API. 

The API consists of a single function `independence(test::IndependenceTest, x, y, [z])`. The two-argument version is for pairwise independence testing, and the three-argument version is for conditional independence testing.

We currently implement the following independence tests:

| Test     | Type | Pairwise/conditional | Compatible with |
| ----------- | ----------- | ----------- | ----------- |
| `SurrogateTest`      | Nonparametric      | Pairwise and conditional | Any `AssociationMeasure` (+ estimator, if relevant). Any `Surrogate` from TimeseriesSurrogates.jl|
| `LocalPermutationTest`   | Nonparametric        | Conditional | Any `AssociationMeasure` (+ estimator, if relevant)  |
| `JointDistanceDistribution`   | Parametric t-test        | Pairwise | Not relevant  |

All currently implement tests return a p-value. Usually, if `p < α`, where `α` is some user-determined significance level, then one would reject the null hypothesis of independence.

### 3. **Causal graph inference measures**. 

- Every graph inference algorithm is a subtype of `GraphAlgorithm`. Graph algorithms can be completely generic (i.e. the PC algorithm below), or specifically designed to infer timeseries graphs (i.e. `OCE` below)
- Currently, we implement `OCE` (optimal causation entropy), but more algorithms are just around the corner. 

- `infer_graph(alg::GraphAlgorithm, x)` takes a set of input timeseries `x` and infers a causal graph. The return type depends on `alg`.

Note that a few causal network inference methods are also available in CausalInference.jl. I think this package is quite nice too, but its design is not compatible with our ecosystem, so everything has been designed from scratch here.

## Summary

As far as I know, the approach that this package takes is pretty unique. It essentially allows you to use *any* `AssociationMeasure` (with *any* of its estimators, if relevant), with *any* compatible pairwise or conditional `IndependenceTest`. In turn, these independence tests may be used with compatible graph algorithms to infer causal networks. I haven't even begun to count to number of possible high-level combinations, but the number is obviously far higher than for ComplexityMeasures.jl. 

Despite thorough review, there is still be some rogue code in the codebase  (i.e. not yet public, or to be removed, or moved to ComplexityMeasures.jl). I will do a final count of methods and "number of possible combinations" once I've finished porting all the un-documented stuff to ComplexityMeasures. 

Everything in the public API should work. But naturally, there are probably some things that we overlooked, so I will also spend the coming weeks/months "putting out fires", as you put it for the new DynamicalSystems.jl release (congratulations, btw, great work! 🥇).

I will make an announcement on Discourse after the remaining non-public methods are finalized in 2.X releases and any bugs we didn't catch in this round are sorted out.

**Comment by kahaaga** [comment]
I forgot to mention:

The 2.0 release contains deprecations for 1.X, which will be removed in 2.1. We will also very soon transition to the new `StateSpaceSets` interface, but that will happen in 2.X.

**Comment by Datseris** [comment]
(I'm putting this on my saved tasks, and will read in detail after the ploen workshop!)

**Comment by kahaaga** [comment]
> What do you mean here? This simply means doing a mass rename of Dataset to StateSpaceSet., and AbstractDataset to AbstractStateSpaceSet, so why not do it immediatelly?

I had some issues with package compatibility when I tried this before all the new DynamicalSystems package were tagged, but it seems to work nicely now! Then Dataset -> StateSpaceSet happens for 2.0. 

> (I'm putting this on my saved tasks, and will read in detail after the ploen workshop!)

No problem. I just thought I'd give a broad overview here, before you start diving into details.
