### ISSUE TITLE
Progress bars in independence tests

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/CausalityTools.jl#341]
Calculating TE is rather fast. However, independence tests can take a while. For example, only with a timeseries of length 3,000, the `LocalPermutationTest` with 50 shuffles takes quite a while.

We should add a progress-bar, that is on by default and is enabled in independence testing. This way, we will have a better idea of the progress of the test.

I'll contribute this, I've added progress bars throughout JuliaDynamics.

**Comment by kahaaga** [comment]
> I'll contribute this, I've added progress bars throughout JuliaDynamics.

Perfect!

**Comment by kahaaga** [comment]
Closed by #343
